#!/usr/bin/env python3
"""Mint the Phase 6 hardware-gate floppy image set, each with a `.baseline` twin.

WHY THIS EXISTS (2026-09-19, docs/floppy_write_plan.md Phase 6 "On hardware,
after a fit"). Phase 6 is the FORMAT phase, and a format writes ADDRESS FIELDS:
a positional error makes a disk unreadable rather than merely wrong, and there
is no volatile mode -- one OSD toggle drives both WRTPRT and `write_ok`, so
every write lands in the user's file immediately. Every gate therefore runs on
a scratch copy with a pristine `.baseline` twin to restore from between runs.

CONTENT IS SELF-IDENTIFYING, not zero fill. Each 512-byte sector carries its
own index, so a mis-positioned write names the sector it landed on instead of
just saying "mismatch" -- the same reasoning as scripts/gcr_gen_image.py. It
also makes the One-Sided erase gate checkable: the plan says the upper half of
a one-sided-erased 800K is REMNANT, and remnant is only distinguishable from
"the core wrote there" if the old data was recognisable in the first place.

THE FAT12 WRITER IS OURS because no FAT writer is installed (no pyfatfs) --
but it is minted against an INDEPENDENT reader: scripts/fat_diff.py, itself
validated against 7-Zip on 2026-09-18. Every FAT image this script emits is
re-read by that reader before the script exits. A writer checked only by its
own reader proves nothing.

* THE 1.44 MB DC42 TAIL IS AN EXACT ALIGNMENT, not an approximation. A tagless
1440K DC42 is 84 + 1,474,560 = 1,474,644 bytes = 2880 whole 512-byte blocks
plus an 84-byte partial block. FAT cluster 2848 -- the LAST cluster -- is
sector 2879, the last sector, so that sector's final 84 bytes ARE the partial
tail block that 6D makes writable. TAIL.BIN is pinned to cluster 2848 on
purpose and its last 84 bytes are a literal signature, so the gate reads
"did the tail survive" straight off the bytes.

OUTPUT IS DETERMINISTIC -- verified 2026-09-19 by minting the set twice into
different directories and comparing md5s. No timestamp, volume serial or
allocation order varies between runs, so a `.baseline` twin that gets lost or
overwritten can be regenerated byte-identically instead of invalidating the
gate it belonged to.

Usage:  python scripts/mint_phase6_images.py [--outdir DIR] [--force]
Exit 0 means every image minted AND re-read cleanly.
"""
import argparse
import pathlib
import shutil
import struct
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent

SEC = 512
# The bench image library on the development machine, alongside the MFM set the
# plan's Phase 5 table records. It is deliberately OUTSIDE the repo: these are
# the user's disks, they get written by hardware, and nothing here is a build
# input. --outdir overrides it on any other machine.
DEFAULT_OUT = pathlib.Path("C:/temp/Mac/Test disks/Phase6")


# ---------------------------------------------------------------- content
def sector_pattern(nbytes, tag, first_sector=0):
    """Self-identifying filler: every 512-byte sector names itself."""
    out = bytearray()
    idx = first_sector
    while len(out) < nbytes:
        head = ("P6 %s SEC%06d " % (tag, idx)).encode("ascii")[:32]
        head = head.ljust(32, b".")
        body = bytes(((idx * 7 + i * 13) & 0xFF) for i in range(SEC - 32))
        out += head + body
        idx += 1
    return bytes(out[:nbytes])


TAIL_SIG = (b"P6-DC42-TAIL-84B-THIS-IS-THE-PARTIAL-FINAL-BLOCK-"
            b"phase6-6D-gate-2026-09-19-okay-END!")
assert len(TAIL_SIG) == 84, len(TAIL_SIG)


# ---------------------------------------------------------------- FAT12
class Fat12Geom:
    def __init__(self, total, spc, root_ents, media, spf, spt, heads, name):
        self.total, self.spc, self.root_ents = total, spc, root_ents
        self.media, self.spf, self.spt, self.heads = media, spf, spt, heads
        self.name = name
        self.reserved, self.nfats = 1, 2
        self.root_secs = root_ents * 32 // SEC
        self.data_start = self.reserved + self.nfats * spf + self.root_secs
        self.n_clusters = (total - self.data_start) // spc
        self.last_cluster = self.n_clusters + 1      # clusters are 2..last


G1440 = Fat12Geom(2880, 1, 224, 0xF0, 9, 18, 2, "1440K")
G720 = Fat12Geom(1440, 2, 112, 0xF9, 3, 9, 2, "720K")


def _fat_set(fat, n, val):
    o = n + (n >> 1)
    if n & 1:
        fat[o] = (fat[o] & 0x0F) | ((val << 4) & 0xF0)
        fat[o + 1] = (val >> 4) & 0xFF
    else:
        fat[o] = val & 0xFF
        fat[o + 1] = (fat[o + 1] & 0xF0) | ((val >> 8) & 0x0F)


def _dirent(name8, ext3, attr, cluster, size):
    e = bytearray(32)
    e[0:8] = name8.upper().ljust(8).encode("ascii")[:8]
    e[8:11] = ext3.upper().ljust(3).encode("ascii")[:3]
    e[11] = attr
    struct.pack_into("<H", e, 22, 0x6000)            # time 12:00:00
    struct.pack_into("<H", e, 24, 0x5D13)            # date
    struct.pack_into("<H", e, 26, cluster)
    struct.pack_into("<I", e, 28, size)
    return bytes(e)


def fat12_mint(geom, label, files, serial=0x50365001):
    """files: list of (name8, ext3, data, pinned_cluster|None), allocated in order."""
    img = bytearray(geom.total * SEC)

    bs = bytearray(SEC)
    bs[0:3] = b"\xEB\x3C\x90"
    bs[3:11] = b"MSDOS5.0"
    struct.pack_into("<H", bs, 11, SEC)
    bs[13] = geom.spc
    struct.pack_into("<H", bs, 14, geom.reserved)
    bs[16] = geom.nfats
    struct.pack_into("<H", bs, 17, geom.root_ents)
    struct.pack_into("<H", bs, 19, geom.total)
    bs[21] = geom.media
    struct.pack_into("<H", bs, 22, geom.spf)
    struct.pack_into("<H", bs, 24, geom.spt)
    struct.pack_into("<H", bs, 26, geom.heads)
    bs[38] = 0x29
    struct.pack_into("<I", bs, 39, serial)
    bs[43:54] = label.upper().ljust(11).encode("ascii")[:11]
    bs[54:62] = b"FAT12   "
    bs[510:512] = b"\x55\xAA"
    img[0:SEC] = bs

    fat = bytearray((geom.last_cluster + 2) * 3 // 2 + 2)
    _fat_set(fat, 0, 0xF00 | geom.media)
    _fat_set(fat, 1, 0xFFF)

    pinned = set(c for (_, _, _, c) in files if c)
    free = (c for c in range(2, geom.last_cluster + 1) if c not in pinned)
    ents = [_dirent(label, "", 0x08, 0, 0)]

    for name8, ext3, data, pin in files:
        csize = geom.spc * SEC
        need = max(1, (len(data) + csize - 1) // csize)
        if pin:
            if need != 1:
                raise ValueError("pinned file must fit one cluster: %s" % name8)
            chain = [pin]
        else:
            chain = [next(free) for _ in range(need)]
        for i, c in enumerate(chain):
            _fat_set(fat, c, 0xFFF if i == need - 1 else chain[i + 1])
            off = (geom.data_start + (c - 2) * geom.spc) * SEC
            img[off:off + csize] = data[i * csize:(i + 1) * csize].ljust(csize, b"\x00")
        ents.append(_dirent(name8, ext3, 0x20, chain[0], len(data)))

    for i in range(geom.nfats):
        off = (geom.reserved + i * geom.spf) * SEC
        img[off:off + len(fat)] = fat
    roff = (geom.reserved + geom.nfats * geom.spf) * SEC
    blob = b"".join(ents)
    if len(blob) > geom.root_secs * SEC:
        raise ValueError("root directory overflow")
    img[roff:roff + len(blob)] = blob
    return bytes(img)


# ---------------------------------------------------------------- HFS
def hfs_mint(volname, size, fill_to):
    import machfs
    v = machfs.Volume()
    v.name = volname
    if fill_to > 0:
        f = machfs.File()
        f.type, f.creator = b"BINA", b"MACS"
        f.data = sector_pattern(int(size * fill_to), volname[:6])
        v["Marker.bin"] = f
    return v.write(size=size, desktopdb=False, bootable=False)


# ---------------------------------------------------------------- helpers
def emit(out, name, blob, force):
    p = out / name
    if p.exists() and not force:
        print("  SKIP (exists, --force to overwrite): %s" % name)
        return p
    p.write_bytes(blob)                       # BINARY -- the line-endings trap
    base = p.with_suffix(".baseline" + p.suffix)
    shutil.copyfile(p, base)
    print("  %-34s %9d  + %s" % (name, len(blob), base.name))
    return p


def run(*args):
    r = subprocess.run([sys.executable] + list(args), capture_output=True, text=True)
    if r.returncode != 0:
        print("    VERIFY FAIL: %s\n%s\n%s" % (args, r.stdout[-1500:], r.stderr[-800:]))
    return r.returncode == 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=str(DEFAULT_OUT))
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    out = pathlib.Path(a.outdir)
    out.mkdir(parents=True, exist_ok=True)
    print("Phase 6 gate images -> %s\n" % out)

    ok = True
    hfs_imgs, fat_imgs = [], []

    # -- gates 1, 2, 4a: 800K GCR targets ---------------------------------
    print("800K GCR (gate 1 Erase, gate 2 One-Sided, gate 4a cross-as-DOS-720K):")
    for nm, vol in (("P6_GCR_Erase800K.dsk", "P6 Erase800"),
                    ("P6_OneSided800K.dsk", "P6 OneSide"),
                    ("P6_Cross800K.dsk", "P6 Cross800")):
        # ~85% full so the pattern reaches well past byte 409,600: the upper
        # half of a one-sided erase must be RECOGNISABLE remnant, not zeros.
        hfs_imgs.append(emit(out, nm, hfs_mint(vol, 819200, 0.85), a.force))

    # -- gate 3 and its control -------------------------------------------
    # The GCR matrix is {800K, 400K} x {One-Sided, Two-Sided}. Gate 1 is the
    # native 800K cell and gate 2 the 800K conflict; gate 3 is the 400K
    # CONFLICT (diskSides holds the ceiling at 0 against a Two-Sided request).
    # The 400K NATIVE cell was missing from the plan's list -- and it is the
    # control that makes gate 3 readable: same path with nothing to clamp, so
    # gate 3's result should come out structurally the same as this one.
    print("\n400K (gate 3 Two-Sided erase, + the One-Sided native control):")
    hfs_imgs.append(emit(out, "P6_TwoSided400K.dsk",
                         hfs_mint("P6 Two400", 409600, 0.70), a.force))
    hfs_imgs.append(emit(out, "P6_OneSided400K.dsk",
                         hfs_mint("P6 One400", 409600, 0.70), a.force))

    # -- gate 6a: blank 1.44 MB HFS for the MFM format gate ---------------
    print("\n1.44 MB HFS (gate 6a MFM format + short soak):")
    hfs_imgs.append(emit(out, "P6_MFM1440K.dsk",
                         hfs_mint("P6 MFM1440", 1474560, 0.0), a.force))

    # -- gates 4b, 6b: 720K DOS -------------------------------------------
    print("\n720K FAT12 (gate 4b cross-as-Mac-800K, gate 6b DOS format):")
    g = G720
    body = sector_pattern(300 * SEC * g.spc, "D720")
    fat_imgs.append(emit(out, "P6_Cross720K.img",
                         fat12_mint(g, "P6CROSS720",
                                    [("FILLER", "BIN", body, None)]), a.force))
    fat_imgs.append(emit(out, "P6_DOS720K.img",
                         fat12_mint(g, "P6DOS720", []), a.force))

    # -- gate 5: the 6D DC42 tail -----------------------------------------
    print("\n1.44 MB FAT12 in DC42 (gate 5, the 6D partial-tail gate):")
    g = G1440
    tail = sector_pattern(SEC - 84, "TAIL") + TAIL_SIG
    assert len(tail) == SEC
    # TAIL.BIN pinned to the LAST cluster: cluster 2848 == sector 2879, whose
    # final 84 bytes are exactly the DC42 partial block 6D makes writable.
    tail_img = fat12_mint(g, "P6TAIL144", [("TAIL", "BIN", tail, g.last_cluster)])
    p = emit(out, "P6_DOS1440_tail.img", tail_img, a.force)
    fat_imgs.append(p)
    blank_img = fat12_mint(g, "P6FILL144", [])
    p2 = emit(out, "P6_DOS1440_fill.img", blank_img, a.force)
    fat_imgs.append(p2)

    print("\n  DC42 wrappers (mk_dc42.py verifies its own output):")
    mk = str(REPO / "scripts" / "mk_dc42.py")
    dc_out = []
    for src, dst, nm in ((p, out / "P6_DOS1440_tail (DC42).img", "P6 tail"),
                         (p2, out / "P6_DOS1440_fill (DC42).img", "P6 fill")):
        dc_out.append(dst)
        if dst.exists() and not a.force:
            print("    SKIP (exists): %s" % dst.name)
            continue
        if run(mk, str(src), str(dst), "--name", nm):
            shutil.copyfile(dst, dst.with_suffix(".baseline" + dst.suffix))
            print("    %-34s %9d  + baseline" % (dst.name, dst.stat().st_size))
        else:
            ok = False

    # -- verification pass -------------------------------------------------
    print("\nVerify (independent readers):")
    for q in hfs_imgs:
        good = run(str(REPO / "scripts" / "hfs_check.py"), str(q))
        print("  hfs_check  %-32s %s" % (q.name, "OK" if good else "FAIL"))
        ok = ok and good
    for q in fat_imgs + dc_out:
        good = run(str(REPO / "scripts" / "fat_diff.py"), str(q))
        print("  fat_diff   %-32s %s" % (q.name, "OK" if good else "FAIL"))
        ok = ok and good

    # -- the tail alignment, asserted on the real bytes --------------------
    t = dc_out[0].read_bytes()
    aligned = t[-84:] == TAIL_SIG
    print("\n  DC42 partial-tail alignment: last 84 bytes == TAIL_SIG -> %s"
          % ("OK" if aligned else "MISMATCH"))
    print("  (file %d B = %d whole blocks + %d)"
          % (len(t), len(t) // SEC, len(t) % SEC))
    ok = ok and aligned

    print("\n%s" % ("ALL IMAGES MINTED AND VERIFIED" if ok else "*** PROBLEMS ABOVE ***"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
